version: '3.9'
services:
    scanner:
        build:
            context: ./
            dockerfile: ./Docker/api/Dockerfile
        restart: unless-stopped
        links: 
            - mongodb
            - weskit
        command: bash -c "source activate weskit; cd /app/binding-scanner; python app.py"
        ports:
            - "80:8080"

    mongodb: 
        image: mongo:3.6
        restart: unless-stopped
        ports:
            - "27017:27017"

    weskit:
        tty: true
        stdin_open: true
        build: ./Docker/weskit/
        restart: unless-stopped
        ports:
            - "3306:3306"


