version: '3.6'
services:

    scanner:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        links: 
            - mongodb
        command: bash -c "cd /app/binding-scanner; python app.py"
        ports:
            - "8080:8080"

    mongodb: 
        image: mongo:3.6
        restart: unless-stopped
        ports:
            - "27018:27018"