version: '3.9'
services:
    scanner:
        build:
            context: ./
            dockerfile: ./Dockerfile
        restart: unless-stopped
        links: 
            - mongodb
            - weskit
        command: bash -c "cd /app/binding-scanner; python app.py"
        ports:
            - "80:8080"

    mongodb: 
        image: mongo:3.6
        restart: unless-stopped
        ports:
            - "27017:27017"

    weskit:
        stdin_open: true
        tty: true
        image: krish8484/weskit:first
        restart: unless-stopped
        command: bash -c "source activate weskit && tail -f /dev/null"
        ports:
            - "3306:3306"


